on:
  push:
    branches:
      - master
  pull_request:
name: ci
jobs:
  add-license:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10, 12, 13]
    env:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - run: (curl http://www.apache.org/licenses/LICENSE-2.0.txt) > LICENSE
      - uses: TomKristie/test-action@v1
        with:
          args: >-
            pr
            -o Octocat
            -r HelloWorld
            -d 'This pull request is adding a LICENSE file'
            -t 'chore(license): add license file'
            -m 'chore(license): add license file'
            -b 'my-branch'
            --git-dir='.'
